language: python

cache: pip

python:
  - 3.6
  - 3.7
  - 3.8

matrix:
  fast_finish: true

before_install:
  # Strangely enough numpy is already installed on Travis's VMs
  - pip uninstall -y numpy
  - pip install -r requirements_dev.txt

install:
  - pip install -e .

script:
  - pytest -xvv tests
  - black --check .
  - safety check
